# Generated by Django 6.0.7 on 2026-07-30 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0001_initial'),
        ('tasks', '0015_task_difficulty_task_estimated_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskWorkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Начало работы')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец работы')),
                ('result', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Завершена'), (2, 'Продолжу позже'), (3, 'Отменена')], null=True, verbose_name='Результат')),
                ('postpone_reason', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Не хватило времени'), (2, 'Меня отвлекли'), (3, 'Появилась срочная работа'), (4, 'Задача оказалась сложнее'), (5, 'Нужна дополнительная информация'), (6, 'Задача больше не актуальна'), (7, 'Другая причина')], null=True, verbose_name='Причина переноса')),
                ('recommendation_order', models.PositiveIntegerField(default=1, verbose_name='Номер рекомендации (1=первая)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Запись работы',
                'verbose_name_plural': 'Записи работы',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.PositiveSmallIntegerField(choices=[(1, 'Низкая'), (2, 'Средняя'), (3, 'Высокая')], verbose_name='Энергия')),
                ('focus', models.PositiveSmallIntegerField(choices=[(1, 'Сложно сосредоточиться'), (2, 'Нормальная концентрация'), (3, 'Могу глубоко работать')], verbose_name='Концентрация')),
                ('available_time', models.PositiveSmallIntegerField(choices=[(1, 'До 30 минут'), (2, '30–90 минут'), (3, 'Больше 90 минут')], verbose_name='Доступное время')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Рабочая сессия',
                'verbose_name_plural': 'Рабочие сессии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='dailystate',
            name='unique_daily_state',
        ),
        migrations.RemoveField(
            model_name='recommendationfeedback',
            name='daily_state',
        ),
        migrations.RemoveField(
            model_name='recommendationfeedback',
            name='task',
        ),
        migrations.RemoveField(
            model_name='recommendationfeedback',
            name='user',
        ),
        migrations.AddField(
            model_name='taskworkrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='tasks.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='taskworkrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_work_records', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='taskworkrecord',
            name='work_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_records', to='focus.worksession', verbose_name='Рабочая сессия'),
        ),
        migrations.RemoveField(
            model_name='dailystate',
            name='user',
        ),
        migrations.DeleteModel(
            name='FocusTask',
        ),
        migrations.DeleteModel(
            name='RecommendationFeedback',
        ),
        migrations.DeleteModel(
            name='DailyState',
        ),
    ]
