# Generated by Django 6.0.7 on 2026-07-29 12:08

import agenda.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(default=agenda.models.make_code, editable=False, max_length=16, unique=True)),
                ('admin_code', models.CharField(default=agenda.models.make_code, editable=False, max_length=16, unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Название обсуждения')),
                ('organizer', models.CharField(max_length=60, verbose_name='Имя организатора')),
                ('meetpoint_url', models.URLField(blank=True, verbose_name='Ссылка на встречу в meet_point')),
                ('summary', models.TextField(blank=True, verbose_name='Итог обсуждения')),
                ('phase', models.CharField(choices=[('collect', 'Сбор тем'), ('done', 'Обсуждение завершено')], default='collect', max_length=10, verbose_name='Фаза')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('next_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='agenda.meeting', verbose_name='Следующая встреча')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Тема')),
                ('author_token', models.CharField(editable=False, max_length=32)),
                ('discussed', models.BooleanField(default=False, verbose_name='Обсудили')),
                ('dropped', models.BooleanField(default=False, verbose_name='Снято с обсуждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='agenda.meeting')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
