# Generated by Django 6.0.7 on 2026-08-01 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('tasks', '0015_task_difficulty_task_estimated_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время выполнения')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отмены')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='agenda.meeting', verbose_name='Встреча')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='tasks.project', verbose_name='Проект')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Итог встречи',
                'verbose_name_plural': 'Итоги встреч',
                'ordering': ['-created_at'],
            },
        ),
    ]
