# Generated by Django 6.0.7 on 2026-07-29 12:08

import django.db.models.deletion
import votes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(default=votes.models.make_code, editable=False, max_length=16, unique=True)),
                ('admin_code', models.CharField(default=votes.models.make_code, editable=False, max_length=16, unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Название доски')),
                ('organizer', models.CharField(max_length=60, verbose_name='Имя организатора')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('phase', models.CharField(choices=[('collect', 'Сбор карточек'), ('vote', 'Голосование'), ('done', 'Завершено')], default='collect', max_length=10, verbose_name='Фаза')),
                ('votes_per_person', models.PositiveSmallIntegerField(default=5, verbose_name='Точек голосования на человека')),
                ('timer_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец фазы по таймеру')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('good', 'Что было хорошо'), ('bad', 'Что было плохо'), ('action', 'Что меняем')], max_length=10, verbose_name='Колонка')),
                ('text', models.CharField(max_length=280, verbose_name='Текст')),
                ('author_token', models.CharField(editable=False, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='votes.board')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_token', models.CharField(editable=False, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='votes.card')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('card', 'voter_token'), name='uniq_vote_per_card')],
            },
        ),
    ]
