# Generated by Django 6.0.7 on 2026-07-29 12:08

import django.db.models.deletion
import django.db.models.functions.text
import meetings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_code', models.CharField(default=meetings.models.make_code, editable=False, max_length=16, unique=True)),
                ('admin_code', models.CharField(default=meetings.models.make_code, editable=False, max_length=16, unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Название встречи')),
                ('organizer', models.CharField(max_length=60, verbose_name='Ваше имя')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('dates', models.JSONField(editable=False)),
                ('time_from', models.PositiveSmallIntegerField()),
                ('time_to', models.PositiveSmallIntegerField()),
                ('slot_minutes', models.PositiveSmallIntegerField(choices=[(30, '30 минут'), (60, '1 час')], default=60)),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=10)),
                ('final_slot', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slots', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.poll')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(models.F('poll'), django.db.models.functions.text.Lower('name'), name='uniq_participant_name_per_poll')],
            },
        ),
    ]
