# Generated by Django 6.0.6 on 2026-07-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'Активен'), (1, 'Завершён')], default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default=1, verbose_name='Приоритет'),
        ),
    ]
