# Generated by Django 6.0.6 on 2026-07-22 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_historyentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.IntegerField(choices=[(0, 'Никогда'), (1, 'Каждый день'), (2, 'Каждую неделю'), (3, 'Каждый месяц'), (4, 'Каждый год')], default=0, verbose_name='Повторение'),
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_templates', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Шаблон проекта',
                'verbose_name_plural': 'Шаблоны проектов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('priority', models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default=1, verbose_name='Приоритет')),
                ('deadline_offset_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Рекомендуемый дедлайн, дней от создания проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_tasks', to='tasks.projecttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Шаблонная задача',
                'verbose_name_plural': 'Шаблонные задачи',
                'ordering': ['created_at'],
            },
        ),
    ]
