# Generated by Django 6.0.6 on 2026-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_recurrence_projecttemplate_templatetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_interval_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Интервал повторения, дней'),
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.IntegerField(choices=[(0, 'Никогда'), (1, 'Каждый день'), (2, 'Каждую неделю'), (3, 'Каждый месяц'), (4, 'Каждый год'), (5, 'Каждые N дней')], default=0, verbose_name='Повторение'),
        ),
    ]
