# Generated by Django 6.0.6 on 2026-07-24 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_recurrence_interval_days_alter_task_recurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_files/%Y/%m/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Файл задачи',
                'verbose_name_plural': 'Файлы задачи',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
