# Generated by Django 6.0.7 on 2026-07-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default=0, verbose_name='Приоритет'),
        ),
    ]
