# Generated by Django 6.0.7 on 2026-07-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='analysis',
            field=models.JSONField(blank=True, null=True, verbose_name='Извлечённые данные'),
        ),
    ]
