# Generated by Django 6.0.7 on 2026-07-26 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_backfill_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_template',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='tasks.projecttemplate', verbose_name='Создан по шаблону'),
        ),
        migrations.AddField(
            model_name='task',
            name='share_code',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True, verbose_name='Код публичной ссылки'),
        ),
    ]
