# Generated by Django 6.0.7 on 2026-07-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_backfill_project_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Простая'), (2, 'Обычная'), (3, 'Сложная')], default=2, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_duration',
            field=models.PositiveSmallIntegerField(choices=[(1, 'До 15 минут'), (2, 'До 30 минут'), (3, 'До 1 часа'), (4, 'Больше 1 часа')], default=2, verbose_name='Примерная длительность'),
        ),
        migrations.AddField(
            model_name='templatetask',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Простая'), (2, 'Обычная'), (3, 'Сложная')], default=2, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='templatetask',
            name='estimated_duration',
            field=models.PositiveSmallIntegerField(choices=[(1, 'До 15 минут'), (2, 'До 30 минут'), (3, 'До 1 часа'), (4, 'Больше 1 часа')], default=2, verbose_name='Примерная длительность'),
        ),
    ]
