# Generated by Django 6.0.7 on 2026-08-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_meetingoutcome'),
        ('tasks', '0015_task_difficulty_task_estimated_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='meeting_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='agenda.meetingoutcome', verbose_name='Итог встречи'),
        ),
    ]
