# Generated by Django 6.0.7 on 2026-08-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_drop_workspace_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='taskfile',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task', verbose_name='Задача'),
        ),
    ]
