# Generated by Django 6.0.7 on 2026-08-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('tasks', '0018_alter_taskfile_options_taskfile_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='integrations.emailmessage', verbose_name='Исходное письмо'),
        ),
    ]
