# Generated by Django 6.0.7 on 2026-08-16 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0018_alter_taskfile_options_taskfile_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='gmail', max_length=20, verbose_name='Провайдер')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта аккаунта')),
                ('encrypted_access_token', models.TextField(verbose_name='Зашифрованный access token')),
                ('encrypted_refresh_token', models.TextField(verbose_name='Зашифрованный refresh token')),
                ('token_expires_at', models.DateTimeField(verbose_name='Срок access token')),
                ('is_active', models.BooleanField(default=True, verbose_name='Подключено')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подключения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_integrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Интеграция почты',
                'verbose_name_plural': 'Интеграции почты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(max_length=255, unique=True, verbose_name='ID письма в Gmail')),
                ('thread_id', models.CharField(blank=True, max_length=255, verbose_name='ID треды')),
                ('sender_name', models.CharField(blank=True, max_length=255, verbose_name='Имя отправителя')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='Почта отправителя')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Тема')),
                ('snippet', models.TextField(blank=True, verbose_name='Фрагмент')),
                ('received_at', models.DateTimeField(verbose_name='Получено')),
                ('gmail_url', models.URLField(blank=True, verbose_name='Ссылка на Gmail')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сохранено')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.emailintegration', verbose_name='Интеграция')),
                ('linked_tasks', models.ManyToManyField(blank=True, related_name='linked_emails', to='tasks.task', verbose_name='Связанные задачи')),
                ('projects', models.ManyToManyField(blank=True, related_name='emails', to='tasks.project', verbose_name='Проекты')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='emailintegration',
            constraint=models.UniqueConstraint(fields=('user', 'provider', 'email'), name='uniq_integration_per_user_provider_email'),
        ),
    ]
