# Generated by Django 6.0.7 on 2026-08-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailintegration',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок access token'),
        ),
    ]
